default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 50000
  username: dota_lounge
  password: 1u!ofS-h_$

development:
  <<: *default
  database: dota_lounge_development

test:
  <<: *default
  database: dota_lounge_test

production:
  <<: *default
  database: dota_lounge_production
  password: <%= ENV['DOTA_LOUNGE_DATABASE_PASSWORD'] %>
